name_or_path: /root/pubmodels/transformers/llama-2/llama-2-7b-chat-hf
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: bfloat16

lora: true