name_or_path: /root/pubmodels/transformers/mistralai/Mistral-7B-v0.1
tokenizer_name_or_path: /root/pubmodels/transformers/chat-models/mistral-7b-sft-beta
archive: null
block_name: MistralDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: bfloat16

lora: false